# wrangler.toml
name = "super-proxy-ahmedyehia22-v2"
main = "worker.js"
compatibility_date = "2025-04-14"
workers_dev = true

# إعدادات الـ Routes
[[routes]]
pattern = "super-proxy-ahmedyehia2-v2.workers.dev/*"
